### ISSUE TITLE
Visual for CreativeTim newsletter 

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/zillah#77] opened 2016-06-07 11:04 UTC
Un vizual in care promovam Zillah pentru newsletterul CreativeTim:

Text: Zillah - free blogging theme for designers
                                                    by ThemeIsle 

Ar trebui sa o avem maine, ca joi dau ei newsletterul.

**Comment by s2abina** [comment] 2016-06-07 15:11
@ineagu ce ziceti de copy-ul asta:

A dashing WordPress theme for (un)sophisticated bloggers

**Comment by ineagu** [comment] 2016-06-08 07:14
I would use something mentioning designers somehow, the tagline can work on
reddit/designernews as well

On Tue, Jun 7, 2016 at 6:11 PM, Sabina Ionescu <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> ce ziceti de copy-ul asta:
>
> A dashing WordPress theme for (un)sophisticated bloggers
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/zillah/issues/77#issuecomment-224312125>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABw6DH8roaEKoi2X9L_BnICOsyH3WeACks5qJYo6gaJpZM4Ivzel>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by s2abina** [comment] 2016-06-08 11:34
How about:
"Made by designers, for designers. The new Zillah WordPress blogging theme."
"New Zillah theme for WordPress lovers. Designed with simplicity in mind." 

Putting 'designers' and 'free' in the same sentence may not be very attractive for them. There's this whole issue about spec work that we should consider.

**Comment by s2abina** [comment] 2016-06-08 11:45
We're going with something shorter for the banner image :)

>> Made by designers, for designers.

**Comment by rodica-andronache** [comment] 2016-06-13 14:11
@abaicus we can close this?

**Closed as completed** 2016-06-13 14:13 UTC
